

---


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quorum-{{ include "quorum.name" . }}-pvc

  annotations:
spec:
  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quorum-{{ include "quorum.name" . }}-log-pvc
  annotations:
spec:
  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
