

---


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quorum-{{- .Values.name -}}-pvc

  annotations:
spec:
  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quorum-{{- .Values.name -}}-tm-pvc
  annotations:
spec:
  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quorum-{{- .Values.name -}}-log-pvc
  annotations:
spec:
  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
