
# TODO: mount this file
---
# kubectl create configmap game-config --from-file=configure-pod-container/dd1/key
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "quorum.name" . }}-quorum-static-nodes-config
    labels:
        app: qubernetes
        name: {{ include "quorum.name" . }}-quorum-static-nodes-config
data:
    static-nodes.json: |+
{{ tpl (.Files.Get "files/static-nodes.json") . | indent 8 }}