
    


---
apiVersion: v1
kind: Service
metadata:
  name: quorum-{{ include "quorum.name" . }}
  labels:
    app: qubernetes
    tier: backend
    name: quorum-{{ include "quorum.name" . }}

spec:
  selector:
    app: qubernetes
    tier: backend
    name: {{ include "quorum.name" . }}-quorum-deployment
  # NodePort | ClusterIP
  type: ClusterIP
  ports:
    - name: wsrpc-listener
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: quorum-listener
      protocol: TCP
      port: 21000
      targetPort: 21000
    - name: raft
      protocol: TCP
      targetPort: 50401
      port: 50401
    

