
    


---
apiVersion: v1
kind: Service
metadata:
  name: quorum-{{ .Values.name  }}
  labels:
    app: qubernetes
    tier: backend
    name: quorum-{{ .Values.name  }}

spec:
  selector:
    app: qubernetes
    tier: backend
    name: {{ .Values.name  }}-quorum-deployment
  # NodePort | ClusterIP
  type: ClusterIP
  ports:
    - name: tm-manager 
      protocol: TCP
      port: 9001
      targetPort: 9001
    # default 8545
    - name: tm-tessera-third-part
      protocol: TCP
      port: 9080
      targetPort: 9080
    # default 8545
    - name: wsrpc-listener
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: quorum-listener
      protocol: TCP
      port: 21000
      targetPort: 21000
    - name: raft
      protocol: TCP
      targetPort: 50401
      port: 50401
    

