---
#ac6b1096ca56b9f6d004b779ae3728bf83f8e22453404cc3cef16a3d9b96608bc67c4b30db88e0a5a6c6390213f7acbe1153ff6d23ce57380104288ae19373ef



# The quorum deployment consists of
# 1. the transaction manager / private tx container (constellation or tessera)
# 2. the quorum node container

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quorum.name" . }}-quorum-deployment

spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      name: {{ include "quorum.name" . }}-quorum-deployment
  template:
    metadata:
      name: {{ include "quorum.name" . }}-quorum-deployment
      labels:
        app: qubernetes
        tier: backend
        name: {{ include "quorum.name" . }}-quorum-deployment

    spec:
      securityContext:
      initContainers:
      - name: quorum-genesis-init-container
        image: quorumengineering/quorum:2.5.0
        command: [ "sh" ]
        args:
        - "-cx"
        - "if [ ! -f $QUORUM_DATA_DIR/genesis_created ]; then
              /usr/local/bin/geth --datadir $QUORUM_DATA_DIR init /etc/quorum/genesis/genesis-geth.json;
              date > $QUORUM_DATA_DIR/genesis_created;
           fi;
          "
        env:
          - name: QUORUM_DATA_DIR
            value: /etc/quorum/qdata/dd
          - name: QHOME
            value: /etc/quorum/qdata
        volumeMounts:
        - name: quorum-persistent-storage
          mountPath:  /etc/quorum/qdata
        - name: genesis-config-persistent-storage
          mountPath: /etc/quorum/genesis/genesis-geth.json
          subPath: genesis-geth.json
      containers:
      - name: quorum
        image: quorumengineering/quorum:2.5.0
        command: [ "sh" ]
        args:
        - "-cx"
        - "
           apk add curl;
           apk add jq;

           ls  $QUORUM_DATA_DIR;
           cat /etc/quorum/genesis/genesis-geth.json;

           chmod 644 $QUORUM_DATA_DIR/keystore/key;
 
           touch $QUORUM_DATA_DIR/password.txt;
           NETWORK_ID=10
           args=\" --gcmode archive --raft  --raftport 50401 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft \";
           PRIVATE_CONFIG=ignore /usr/local/bin/geth \
           --datadir $QUORUM_DATA_DIR \
           $args \
           --nat=none \
           --verbosity 9 \
           --networkid $NETWORK_ID \
           --unlock 0 \
           --emitcheckpoints \
           --rpc \
           --rpcaddr 0.0.0.0 \
           --rpcport 8546 \
           --port 21000 \
            \
           --password $QUORUM_DATA_DIR/password.txt 2>&1 | tee -a /etc/quorum/qdata/logs/quorum.log;"
        ports:
          - containerPort: 50401
          - containerPort: 8546
          - containerPort: 21000
        env:
        - name: QUORUM_DATA_DIR
          value: /etc/quorum/qdata/dd
        - name: QUORUM_HOME
          value: /etc/quorum/qdata
        - name: QHOME
          value: /etc/quorum/qdata
        volumeMounts:
        - name: genesis-config-persistent-storage
          mountPath: /etc/quorum/genesis/genesis-geth.json
          subPath: genesis-geth.json
        - name: quorum-persistent-storage
          mountPath: /etc/quorum/qdata
        - name: quorum-key-config-persistent-storage
          mountPath: /etc/quorum/qdata/dd/keystore/key
          subPath: key
        - name: quorum-logs-persistent-storage
          mountPath: /etc/quorum/qdata/logs
        - name: quorum-nodekey
          mountPath: /etc/quorum/qdata/dd/geth/nodekey
          subPath: nodekey
        - name: quorum-enode
          mountPath: /etc/quorum/qdata/dd/geth/enode
          subPath: enode
      volumes:
      - name: genesis-config-persistent-storage
        configMap:
          name: {{ include "quorum.name" . }}-genesis-config
          items:
          - key: genesis-geth.json
            path: genesis-geth.json
      - name: quorum-key-config-persistent-storage
        configMap:
          name: quorum-{{ include "quorum.name" . }}-account-key-config
          items:
          - key: key
            path: key
      - name: quorum-nodekey
        configMap:
          name: quorum-{{ include "quorum.name" . }}-nodekey-config
          items:
          - key: nodekey
            path: nodekey
      - name: quorum-enode
        configMap:
          name: quorum-{{ include "quorum.name" . }}-enode-config
          items:
            - key: enode
              path: enode
      - name: quorum-persistent-storage
        persistentVolumeClaim:
          claimName:  quorum-{{ include "quorum.name" . }}-pvc
      - name: quorum-logs-persistent-storage
        persistentVolumeClaim:
          claimName: quorum-{{ include "quorum.name" . }}-log-pvc


