
---
apiVersion: v1
kind: Service
metadata:
  name: quorum-node1-ext
  labels:
    app: qubernetes
    tier: backend
    name: quorum-node1
spec:
  selector:
    app: qubernetes
    tier: backend
    name: quorum-node1-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8546
