{{- range tuple 1 2 3 4 5 6 7 }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: quorum-node{{.}}-ingress-rel
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  rules:
  - host: quorum-node{{.}}-rpc.quorum.cn.blockchain.thoughtworks.cn
    http:
      paths:
      - path: /
        backend:
          serviceName: quorum-node{{.}}
          servicePort: 8546
{{- end }}
