name: Quorum CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      NAMESPACE: quorum-namespace

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Create namespace if not exist
      run: |
        aws eks update-kubeconfig --region cn-northwest-1 --name cn-eks-c0
        kubectl get namespaces $NAMESPACE || kubectl create namespace $NAMESPACE
    
    - name: Deploy
      env:
        RELEASE_NAME: quorum
        CHART: ./
      run: |
        helm -n $NAMESPACE upgrade --install $RELEASE_NAME $CHART